In [1]:
import numpy as np

# Nan
Filter nan

In [11]:
vec = np.array([0, 1, np.nan, 3])
np.isnan(vec)

array([False, False,  True, False], dtype=bool)

In [12]:
~np.isnan(vec)

array([ True,  True, False,  True], dtype=bool)

nan $\neq$ nan

In [13]:
vec == np.nan

array([False, False, False, False], dtype=bool)

In [14]:
vec != np.nan

array([ True,  True,  True,  True], dtype=bool)