In [17]:
import numpy as np

# Matrix Appending
## Initialization
Initialize an empty matrix with given `dim` using `reshape`.

In [19]:
dim = 3
X = np.array([]).reshape(dim, 0)
X

array([], shape=(3, 0), dtype=float64)

## Append Vec 
Append col-vec to matrix along col.

In [51]:
vec = [1, 2, 3]
Y = np.c_[X, vec]
Y

array([[ 1.],
       [ 2.],
       [ 3.]])

In [52]:
Y = np.c_[Y, vec]
Y

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

## Append Mat
Append a matrix along col, differs in dim of axis=1

Convert vec to mat by `expand_dims`

In [53]:
mat = np.expand_dims(vec, axis=1)
mat

array([[1],
       [2],
       [3]])

In [54]:
np.hstack((Y, mat))

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])